name: Documentation

on:
  pull_request:
    branches: [main]
    paths:
      - "**.md"
      - "docs/**"
      - "*.md"
      - ".github/workflows/documentation.yml"
  push:
    branches: [main]
    paths:
      - "**.md"
      - "docs/**"
      - "*.md"
      - ".github/workflows/documentation.yml"

jobs:
  lint-docs:
    name: Lint Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install markdownlint
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown files
        run: |
          # Get list of changed files
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          fi

          # Check if workflow file was changed - if so, lint all markdown
          if echo "$CHANGED_FILES" | grep -q ".github/workflows/documentation.yml"; then
            echo "Workflow file changed, linting all markdown files"
            markdownlint-cli2 .
          else
            # Filter for markdown files only
            MARKDOWN_FILES=$(echo "$CHANGED_FILES" | grep -E '\.(md|markdown)$' || true)
            if [ -n "$MARKDOWN_FILES" ]; then
              echo "Linting changed markdown files: $MARKDOWN_FILES"
              echo "$MARKDOWN_FILES" | xargs markdownlint-cli2
            else
              echo "No markdown files changed"
            fi
          fi

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"

  validate-docs:
    name: Validate Documentation Structure
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check required documentation files
        run: |
          # Check for required files
          if [ ! -f "README.md" ]; then
            echo "❌ README.md is missing"
            exit 1
          fi

          if [ ! -f "LICENSE" ]; then
            echo "❌ LICENSE file is missing"
            exit 1
          fi

          echo "✅ Documentation structure looks good"
