name: Matrix Example

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/matrix.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        plugins:
          - repository: callumalpass/tasknotes
            ref: d027152
            directory: ""
            build-directory: ""
    uses: ./.github/workflows/build.yml
    with:
      plugin-repository: ${{ matrix.plugins.repository }}
      plugin-ref: ${{ matrix.plugins.ref }}
      plugin-directory: ${{ matrix.plugins.directory }}
      build-directory: ${{ matrix.plugins.build-directory }}
