name: Release Dragonglass Build CLI

on:
  push:
    tags:
      - "dragonglass-build/v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., dragonglass-build/v1.0.0)"
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Dragonglass Build CLI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          # Extract just the version part (v1.0.0) from dragonglass-build/v1.0.0
          CLEAN_VERSION="${VERSION#dragonglass-build/}"
          echo "version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT
          echo "full_tag=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build CLI binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ steps.version.outputs.version }}
          CGO_ENABLED: 0
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          LDFLAGS="-s -w -X 'main.Version=${VERSION}' -X 'main.Commit=${COMMIT_HASH}' -X 'main.BuildTime=${BUILD_TIME}'"

          go build -ldflags="${LDFLAGS}" -o dragonglass-build-${{ matrix.suffix }} ./cmd/dragonglass-build

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dragonglass-build-${{ matrix.suffix }}

      - name: Create tarball
        run: |
          tar -czf dragonglass-build-${{ steps.version.outputs.version }}-${{ matrix.suffix }}.tar.gz \
            dragonglass-build-${{ matrix.suffix }} \
            README.md \
            LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragonglass-build-${{ steps.version.outputs.version }}-${{ matrix.suffix }}
          path: dragonglass-build-${{ steps.version.outputs.version }}-${{ matrix.suffix }}.tar.gz

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/dragonglass-build/')
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get version
        id: version
        run: |
          FULL_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${FULL_TAG#dragonglass-build/}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "full_tag=${FULL_TAG}" >> $GITHUB_OUTPUT

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.tar.gz" -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Generate checksums
        run: |
          cd release-assets
          sha256sum *.tar.gz > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.full_tag }}
          name: Dragonglass Build CLI ${{ steps.version.outputs.version }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true
          files: |
            release-assets/*.tar.gz
            release-assets/checksums.txt
          body: |
            ## Dragonglass Build CLI ${{ steps.version.outputs.version }}

            CLI tool to build Obsidian plugins using Dagger with reproducible builds.

            ### Installation

            **macOS (Apple Silicon)**:
            ```bash
            curl -L -o dragonglass-build.tar.gz https://github.com/gillisandrew/dragonglass-poc/releases/download/${{ steps.version.outputs.full_tag }}/dragonglass-build-${{ steps.version.outputs.version }}-darwin-arm64.tar.gz
            tar -xzf dragonglass-build.tar.gz
            chmod +x dragonglass-build-darwin-arm64
            sudo mv dragonglass-build-darwin-arm64 /usr/local/bin/dragonglass-build
            ```

            **macOS (Intel)**:
            ```bash
            curl -L -o dragonglass-build.tar.gz https://github.com/gillisandrew/dragonglass-poc/releases/download/${{ steps.version.outputs.full_tag }}/dragonglass-build-${{ steps.version.outputs.version }}-darwin-amd64.tar.gz
            tar -xzf dragonglass-build.tar.gz
            chmod +x dragonglass-build-darwin-amd64
            sudo mv dragonglass-build-darwin-amd64 /usr/local/bin/dragonglass-build
            ```

            **Linux (x64)**:
            ```bash
            curl -L -o dragonglass-build.tar.gz https://github.com/gillisandrew/dragonglass-poc/releases/download/${{ steps.version.outputs.full_tag }}/dragonglass-build-${{ steps.version.outputs.version }}-linux-amd64.tar.gz
            tar -xzf dragonglass-build.tar.gz
            chmod +x dragonglass-build-linux-amd64
            sudo mv dragonglass-build-linux-amd64 /usr/local/bin/dragonglass-build
            ```

            ### Usage

            ```bash
            # Build plugin from remote repository
            dragonglass-build https://github.com/user/repo.git --ref main

            # Build plugin from local directory
            dragonglass-build ./plugin-directory

            # Build from specific commit
            dragonglass-build https://github.com/user/repo.git --commit abc123def456
            ```

            ### OCI Installation (Alternative)

            You can also install using ORAS from the GitHub Container Registry:

            ```bash
            # Pull the OCI artifact
            oras pull ${{ env.REGISTRY }}/gillisandrew/dragonglass-build:${{ steps.version.outputs.version }}

            # Make executable and install
            chmod +x dragonglass-build-*
            sudo mv dragonglass-build-<your-platform> /usr/local/bin/dragonglass-build
            ```

            ### Verification

            This release includes build provenance attestations and SBOM for supply chain security:

            ```bash
            # Verify checksums
            sha256sum -c checksums.txt

            # Verify provenance using GitHub CLI (requires gh CLI)
            gh attestation verify dragonglass-build-darwin-arm64 --owner gillisandrew

            # For OCI artifacts, attestations are automatically verified when pulling
            oras pull ghcr.io/gillisandrew/dragonglass-build:${{ steps.version.outputs.version }} --verbose
            ```

  create-oci-artifacts:
    name: Create OCI Artifacts
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ORAS
        uses: oras-project/setup-oras@v1

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          CLEAN_VERSION="${VERSION#dragonglass-build/}"
          echo "version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT
          echo "full_tag=${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Prepare OCI artifacts
        run: |
          mkdir -p oci-artifacts

          # Extract and copy all binaries
          find artifacts -name "*.tar.gz" -exec tar -C oci-artifacts -xzf {} \;

          # Copy documentation
          cp README.md LICENSE oci-artifacts/

          ls -la oci-artifacts/

      - name: Push OCI artifact
        id: push
        run: |
          cd oci-artifacts
          DIGEST=$(oras push ${{ env.REGISTRY }}/gillisandrew/dragonglass-build:${{ steps.version.outputs.version }} \
            --annotation "org.opencontainers.image.title=Dragonglass Build CLI" \
            --annotation "org.opencontainers.image.description=CLI tool to build Obsidian plugins using Dagger with reproducible builds" \
            --annotation "org.opencontainers.image.version=${{ steps.version.outputs.version }}" \
            --annotation "org.opencontainers.image.source=https://github.com/gillisandrew/dragonglass-poc" \
            --annotation "org.opencontainers.image.licenses=MIT" \
            dragonglass-build-* README.md LICENSE | grep -o 'sha256:[a-f0-9]\{64\}')

          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

          # Also tag as latest if this is not a pre-release
          if [[ ! "${{ steps.version.outputs.version }}" =~ "-" ]]; then
            oras tag ${{ env.REGISTRY }}/gillisandrew/dragonglass-build:${{ steps.version.outputs.version }} latest
          fi

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: spdx-json
          upload-artifact: true

      - name: Attest SBOM
        uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ env.REGISTRY }}/gillisandrew/dragonglass-build
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: ./_manifest/sbom.spdx.json
          push-to-registry: true

      - name: Attest build provenance for OCI artifact
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/gillisandrew/dragonglass-build
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
